-- Script (DDL) con el borrado y creado de la tabla temporal. Debe tener el
-- siguiente formato: [MIA]ScriptTT_#CARNET.sql

------------------------------------ CREANDO TABLA TEMPORAL ------------------------------------
CREATE TABLE temporal(
	NOMBRE_CLIENTE VARCHAR,
	CORREO_CLIENTE VARCHAR,
	CLIENTE_ACTIVO VARCHAR,
	FECHA_CREACION VARCHAR,
	TIENDA_PREFERIDA VARCHAR,
	DIRECCION_CLIENTE VARCHAR,
	CODIGO_POSTAL_CLIENTE VARCHAR,
	CIUDAD_CLIENTE VARCHAR,
	PAIS_CLIENTE VARCHAR,
	FECHA_RENTA VARCHAR,
	FECHA_RETORNO VARCHAR,
	MONTO_A_PAGAR VARCHAR,
	FECHA_PAGO VARCHAR,
	NOMBRE_EMPLEADO VARCHAR,
	CORREO_EMPLEADO VARCHAR,
	EMPLEADO_ACTIVO VARCHAR,
	TIENDA_EMPLEADO VARCHAR,
	USUARIO_EMPLEADO VARCHAR,
	PASSWORD_EMPLEADO VARCHAR,
	DIRECCION_EMPLEADO VARCHAR,
	CODIGO_POSTAL_EMPLEADO VARCHAR,
	CIUDAD_EMPLEADO VARCHAR,
	PAIS_EMPLEADO VARCHAR,
	NOMBRE_TIENDA VARCHAR,
	ENCARGADO_TIENDA VARCHAR,
	DIRECCION_TIENDA VARCHAR,
	CODIGO_POSTAL_TIENDA VARCHAR,
	CIUDAD_TIENDA VARCHAR,
	PAIS_TIENDA VARCHAR,
	TIENDA_PELICULA VARCHAR,
	NOMBRE_PELICULA VARCHAR,
	DESCRIPCION_PELICULA VARCHAR,
	LANZAMIENTO_YEAR VARCHAR,
	DIAS_RENTA VARCHAR,
	COSTO_RENTA	VARCHAR,
	DURACION VARCHAR,
	COSTO_POR_DAMAGE VARCHAR,
	CLASIFICACION VARCHAR,
	LENGUAJE_PELICULA VARCHAR,
	CATEGORIA_PELICULA VARCHAR,
	ACTOR_PELICULA VARCHAR
);

------------------------------------ LLENA LA TALBA TEMPORAL MASIVAMENTE ------------------------------------
COPY temporal from '/home/abraham/Escritorio/BlockbusterData.csv' USING delimiters ';' csv header encoding 'windows-1251';

-- MOSTRAR CONTENIDO DE LA TABLA TEMPORAL.
SELECT*FROM temporal;
-- ELIMINA LOS DATOS DE LA TABLA TEMPORAL.
DELETE FROM temporal;
-- ELIMINAR TABLA TEMPORAL.
DROP TABLE temporal;
